const Product = require('../models/Product');
const { uploadToS3, deleteFromS3 } = require('../middleware/upload');

// Helper function to parse boolean values (Form-data converts everything to strings)
const parseBoolean = (value) => value === "true" || value === true;

// 1. ADD PRODUCT
exports.addProduct = async (req, res) => {
    try {
        const {
            name, description, price, originalPrice, salePrice,
            stock, subCategory, bestseller,
            onSale, saleStartDate, saleEndDate,
            hasVariants, variants: variantsStr
        } = req.body;

        const isVariantProduct = parseBoolean(hasVariants);

        // --- AUTOMATIC SKU GENERATION ---
        const subCode = subCategory.substring(0, 3).toUpperCase();
        const uniqueId = Date.now().toString().slice(-6);
        const autoGeneratedSku = `${subCode}-${uniqueId}`;

        let productData = {
            sku: autoGeneratedSku,
            name,
            description,
            originalPrice: Number(originalPrice),
            price: Number(price),
            salePrice: parseBoolean(onSale) ? Number(salePrice) : null,
            stock: Number(stock) || 0,
            subCategory,
            bestseller: parseBoolean(bestseller),
            onSale: parseBoolean(onSale),
            saleStartDate: parseBoolean(onSale) ? saleStartDate : null,
            saleEndDate: parseBoolean(onSale) ? saleEndDate : null,
            hasVariants: isVariantProduct,
            images: [],
            variants: []
        };

        if (isVariantProduct && variantsStr) {
            // --- VARIANT PRODUCT ---
            let parsedVariants = [];
            try {
                parsedVariants = JSON.parse(variantsStr);
            } catch (e) {
                return res.status(400).json({ success: false, message: "Invalid variants data" });
            }

            // Process each variant
            const processedVariants = [];
            for (let i = 0; i < parsedVariants.length; i++) {
                const variant = parsedVariants[i];
                const variantSku = `${autoGeneratedSku}-${variant.color.toUpperCase().replace(/\s+/g, '')}`;

                // Upload variant images from req.files
                // Files are sent with field name like 'variant_0_images', 'variant_1_images'
                const variantFileKey = `variant_${i}`;
                const variantFiles = req.files ? req.files.filter(f => f.fieldname === variantFileKey) : [];

                const variantImages = await Promise.all(
                    variantFiles.map(async (file) => {
                        const result = await uploadToS3(file);
                        return { url: result.url, publicId: result.key };
                    })
                );

                processedVariants.push({
                    color: variant.color,
                    images: variantImages,
                    sizes: (variant.sizes || []).map(s => ({
                        size: s.size,
                        stock: Number(s.stock) || 0,
                        priceAdjustment: Number(s.priceAdjustment) || 0
                    })),
                    sku: variantSku
                });
            }

            productData.variants = processedVariants;

            // Calculate total stock from all variants
            productData.stock = processedVariants.reduce((total, v) => {
                return total + v.sizes.reduce((sTotal, s) => sTotal + s.stock, 0);
            }, 0);

            // Use first variant's first image as the product's main image
            if (processedVariants.length > 0 && processedVariants[0].images.length > 0) {
                productData.images = [processedVariants[0].images[0]];
            }

        } else {
            // --- NON-VARIANT PRODUCT (Legacy behavior) ---
            if (!req.files || req.files.length === 0) {
                return res.status(400).json({ success: false, message: "Please upload at least one product image!" });
            }

            // S3 pe images upload karo
            const images = await Promise.all(
                req.files.map(async (file) => {
                    const result = await uploadToS3(file);
                    return { url: result.url, publicId: result.key };
                })
            );

            productData.images = images;
        }

        const newProduct = new Product(productData);
        await newProduct.save();

        res.status(201).json({
            success: true,
            message: `Product added! SKU: ${autoGeneratedSku}`,
            product: newProduct
        });

    } catch (error) {
        console.error("Add Error:", error.message);
        res.status(500).json({ success: false, message: error.message });
    }
};

// 2. GET ALL PRODUCTS
exports.getAllProducts = async (req, res) => {
    try {
        const products = await Product.find().sort({ createdAt: -1 });
        res.status(200).json({ success: true, products });
    } catch (error) {
        res.status(500).json({ success: false, message: "Error fetching products" });
    }
};

// 3. DELETE PRODUCT
exports.deleteProduct = async (req, res) => {
    try {
        const { id } = req.body;
        const product = await Product.findById(id);

        if (!product) {
            return res.status(404).json({ success: false, message: "Product not found" });
        }

        // Delete main product images from S3
        if (product.images && product.images.length > 0) {
            await Promise.all(
                product.images
                    .filter(img => img.publicId)
                    .map(img => deleteFromS3(img.publicId))
            );
        }

        // Delete variant images from S3
        if (product.variants && product.variants.length > 0) {
            for (const variant of product.variants) {
                if (variant.images && variant.images.length > 0) {
                    await Promise.all(
                        variant.images
                            .filter(img => img.publicId)
                            .map(img => deleteFromS3(img.publicId))
                    );
                }
            }
        }

        await Product.findByIdAndDelete(id);
        res.status(200).json({ success: true, message: "Product and images deleted successfully" });

    } catch (error) {
        console.error("❌ Delete Error:", error.message);
        res.status(500).json({ success: false, message: "Error deleting product" });
    }
};

// 4. SINGLE PRODUCT DETAILS
exports.singleProduct = async (req, res) => {
    try {
        const { productId } = req.body;
        const product = await Product.findById(productId);
        product
            ? res.json({ success: true, product })
            : res.json({ success: false, message: "Product not found" });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

// 5. UPDATE PRODUCT
exports.updateProduct = async (req, res) => {
    try {
        const { id, name, description, price, originalPrice, salePrice, stock, subCategory, bestseller, onSale, saleStartDate, saleEndDate, existingImages: existingImagesStr, hasVariants, variants: variantsStr, existingVariants: existingVariantsStr } = req.body;

        const product = await Product.findById(id);
        if (!product) {
            return res.status(404).json({ success: false, message: "Product not found!" });
        }

        const isVariantProduct = parseBoolean(hasVariants);

        let updateData = {
            name,
            description,
            originalPrice: Number(originalPrice),
            price: Number(price),
            stock: Number(stock),
            subCategory,
            bestseller: parseBoolean(bestseller),
            onSale: parseBoolean(onSale),
            salePrice: parseBoolean(onSale) ? Number(salePrice) : null,
            saleStartDate: parseBoolean(onSale) ? saleStartDate : null,
            saleEndDate: parseBoolean(onSale) ? saleEndDate : null,
            hasVariants: isVariantProduct,
        };

        if (isVariantProduct && variantsStr) {
            // --- UPDATE VARIANT PRODUCT ---
            let parsedVariants = [];
            try {
                parsedVariants = JSON.parse(variantsStr);
            } catch (e) {
                return res.status(400).json({ success: false, message: "Invalid variants data" });
            }

            // Parse existing variant images to keep
            let existingVariantsData = [];
            if (existingVariantsStr) {
                try {
                    existingVariantsData = JSON.parse(existingVariantsStr);
                } catch (e) {
                    existingVariantsData = [];
                }
            }

            // Delete old variant images that are no longer referenced
            const allKeptImageIds = new Set();
            existingVariantsData.forEach(v => {
                (v.images || []).forEach(img => {
                    if (img.publicId) allKeptImageIds.add(img.publicId);
                });
            });

            // Delete removed variant images from S3
            if (product.variants && product.variants.length > 0) {
                for (const oldVariant of product.variants) {
                    for (const img of (oldVariant.images || [])) {
                        if (img.publicId && !allKeptImageIds.has(img.publicId)) {
                            try {
                                await deleteFromS3(img.publicId);
                            } catch (e) {
                                console.error("Failed to delete variant image:", e.message);
                            }
                        }
                    }
                }
            }

            const processedVariants = [];
            for (let i = 0; i < parsedVariants.length; i++) {
                const variant = parsedVariants[i];
                const variantSku = variant.sku || `${product.sku}-${variant.color.toUpperCase().replace(/\s+/g, '')}`;

                // Get existing images for this variant
                const existingVarImages = existingVariantsData[i]?.images || [];

                // Upload new variant images
                const variantFileKey = `variant_${i}`;
                const variantFiles = req.files ? req.files.filter(f => f.fieldname === variantFileKey) : [];

                const newUploadedImages = await Promise.all(
                    variantFiles.map(async (file) => {
                        const result = await uploadToS3(file);
                        return { url: result.url, publicId: result.key };
                    })
                );

                processedVariants.push({
                    color: variant.color,
                    images: [...existingVarImages, ...newUploadedImages],
                    sizes: (variant.sizes || []).map(s => ({
                        size: s.size,
                        stock: Number(s.stock) || 0,
                        priceAdjustment: Number(s.priceAdjustment) || 0
                    })),
                    sku: variantSku
                });
            }

            updateData.variants = processedVariants;

            // Calculate total stock from all variants
            updateData.stock = processedVariants.reduce((total, v) => {
                return total + v.sizes.reduce((sTotal, s) => sTotal + s.stock, 0);
            }, 0);

            // Use first variant's first image as the product's main image
            if (processedVariants.length > 0 && processedVariants[0].images.length > 0) {
                updateData.images = [processedVariants[0].images[0]];
            }

        } else {
            // --- NON-VARIANT PRODUCT (Legacy behavior) ---
            updateData.variants = [];
            updateData.hasVariants = false;

            // Parse existing images that user wants to KEEP
            let keptImages = [];
            if (existingImagesStr) {
                try {
                    keptImages = JSON.parse(existingImagesStr);
                } catch (e) {
                    keptImages = [];
                }
            }

            // Find which old images were REMOVED by user
            const keptPublicIds = keptImages.map(img => img.publicId);
            const removedImages = (product.images || []).filter(
                img => img.publicId && !keptPublicIds.includes(img.publicId)
            );

            // Delete removed images from S3
            if (removedImages.length > 0) {
                await Promise.all(
                    removedImages.map(img => deleteFromS3(img.publicId))
                );
            }

            // Upload new images to S3 (if any)
            let newUploadedImages = [];
            if (req.files && req.files.length > 0) {
                newUploadedImages = await Promise.all(
                    req.files.map(async (file) => {
                        const result = await uploadToS3(file);
                        return { url: result.url, publicId: result.key };
                    })
                );
            }

            // Final images = kept existing + newly uploaded
            updateData.images = [...keptImages, ...newUploadedImages];
        }

        const updatedProduct = await Product.findByIdAndUpdate(id, updateData, { new: true });
        res.json({ success: true, message: "Product updated successfully!", product: updatedProduct });

    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};