const Product = require('../models/Product');
const cloudinary = require('cloudinary').v2;

// Helper function to parse boolean values (Form-data converts everything to strings)
const parseBoolean = (value) => value === "true" || value === true;

// 1. ADD PRODUCT
exports.addProduct = async (req, res) => {
    try {
        const {
            name, description, price, originalPrice, salePrice,
            stock, subCategory, bestseller,
            onSale, saleStartDate, saleEndDate
        } = req.body;

        // Multer-storage-cloudinary image check
        if (!req.files || req.files.length === 0) {
            return res.status(400).json({ success: false, message: "Bhai, product ki photo toh daal!" });
        }

        // --- AUTOMATIC SKU GENERATION ---
        const subCode = subCategory.substring(0, 3).toUpperCase();
        const uniqueId = Date.now().toString().slice(-6);
        const autoGeneratedSku = `${subCode}-${uniqueId}`;

        /* NOTE: Yahan se cloudinary.uploader.upload hata diya gaya hai.
           Kyunki Multer ne req.file.path mein pehle hi Cloudinary URL de diya hai.
        */

        const images = req.files.map((file) => ({
            url: file.path,
            publicId: file.filename
        }));

        const newProduct = new Product({
            sku: autoGeneratedSku,
            name,
            description,
            originalPrice: Number(originalPrice),
            price: Number(price),
            salePrice: parseBoolean(onSale) ? Number(salePrice) : null,
            stock: Number(stock),
            // category,
            subCategory,
            bestseller: parseBoolean(bestseller),
            onSale: parseBoolean(onSale),
            saleStartDate: parseBoolean(onSale) ? saleStartDate : null,
            saleEndDate: parseBoolean(onSale) ? saleEndDate : null,
            images
        });

        await newProduct.save();

        res.status(201).json({
            success: true,
            message: `Product added! SKU: ${autoGeneratedSku}`,
            product: newProduct
        });

    } catch (error) {
        console.error("Add Error:", error.message);
        res.status(500).json({ success: false, message: error.message });
    }
};

// 2. GET ALL PRODUCTS
exports.getAllProducts = async (req, res) => {
    try {
        const products = await Product.find().sort({ createdAt: -1 });
        res.status(200).json({ success: true, products });
    } catch (error) {
        res.status(500).json({ success: false, message: "Error fetching products" });
    }
};

// 3. DELETE PRODUCT
exports.deleteProduct = async (req, res) => {
    try {
        const { id } = req.body;
        const product = await Product.findById(id);

        if (!product) {
            return res.status(404).json({ success: false, message: "Product not found" });
        }

        // Cloudinary se saari images delete karein using saved Public IDs
        if (product.images && product.images.length > 0) {
            await Promise.all(
                product.images
                    .filter(img => img.publicId)
                    .map(img => cloudinary.uploader.destroy(img.publicId))
            );
        }

        await Product.findByIdAndDelete(id);
        res.status(200).json({ success: true, message: "Product and image deleted successfully" });

    } catch (error) {
        console.error("❌ Delete Error:", error.message);
        res.status(500).json({ success: false, message: "Error deleting product" });
    }
};

// 4. SINGLE PRODUCT DETAILS
exports.singleProduct = async (req, res) => {
    try {
        const { productId } = req.body;
        const product = await Product.findById(productId);
        product
            ? res.json({ success: true, product })
            : res.json({ success: false, message: "Product not found" });
    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};

// 5. UPDATE PRODUCT
exports.updateProduct = async (req, res) => {
    try {
        const { id, name, description, price, originalPrice, salePrice, stock, subCategory, bestseller, onSale, saleStartDate, saleEndDate } = req.body;

        const product = await Product.findById(id);
        if (!product) {
            return res.status(404).json({ success: false, message: "Product nahi mila!" });
        }

        let updateData = {
            name,
            description,
            originalPrice: Number(originalPrice),
            price: Number(price),
            stock: Number(stock),
            // category,
            subCategory,
            bestseller: parseBoolean(bestseller),
            onSale: parseBoolean(onSale),
            salePrice: parseBoolean(onSale) ? Number(salePrice) : null,
            saleStartDate: parseBoolean(onSale) ? saleStartDate : null,
            saleEndDate: parseBoolean(onSale) ? saleEndDate : null,
        };

        // Agar nayi files upload hui hain
        if (req.files && req.files.length > 0) {
            // Purani images delete karo Cloudinary se
            if (product.images && product.images.length > 0) {
                await Promise.all(
                    product.images
                        .filter(img => img.publicId)
                        .map(img => cloudinary.uploader.destroy(img.publicId))
                );
            }

            // Nayi images details set karo (Multer ne pehle hi upload kar di hai)
            updateData.images = req.files.map((file) => ({
                url: file.path,
                publicId: file.filename
            }));
        }

        const updatedProduct = await Product.findByIdAndUpdate(id, updateData, { new: true });
        res.json({ success: true, message: "Product updated successfully!", product: updatedProduct });

    } catch (error) {
        res.status(500).json({ success: false, message: error.message });
    }
};